version: '3.9'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
      - PORT=5000
      # - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
  #     # - kafka

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"

  # zookeeper:
  #   image: bitnami/zookeeper:latest
  #   ports:
  #     - "2183:2183"

  # kafka:
  #   image: bitnami/kafka:latest
  #   ports:
  #     - "9090:9090"
  #   environment:
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2183
  #     KAFKA_ADVERTISED_LISTENERS : PLAINTEXT://kafka:9090
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR : 1 
  #   depends_on:
  #     - zookeeper

