version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
      - PORT=5000
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_LISTENER_PORT: 9092
      KAFKA_LISTENER_HOSTNAME_OVERRIDE: kafka
      KAFKA_LISTENER_INTERNAL: INSIDE
      KAFKA_LISTENER_OUTSIDE: OUTSIDE
      KAFKA_LISTENER_MODE: default
    depends_on:
      - zookeeper
